# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12203d0b9555865f3ebcb9fc4670c5c46555e6458fbc51eb4620cfef8123a9640c90";
    path = fetchzip {
      url = "https://github.com/mitchellh/libxev/archive/990ebb3be53f6f10e79504d74d77d2c4f95bbce0.tar.gz";
      hash = "sha256-VpVLjew5hbaD1BxGwAIPYL/bTCJfzmVYWzH0/CKZ1Jw=";
    };
  }
  {
    name = "1220658712708a8625063fb94faf77e17a7da92af69ee3108413df4e247a195ef3b6";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wlroots/archive/87a41e661e37e310f65225e7945a3dfbe7919654.tar.gz";
      hash = "sha256-E3sIcfVqr4k3YhI8Sdr2Xvjn41LgWeW6+mvBseyuFb4=";
    };
  }
  {
    name = "1220687c8c47a48ba285d26a05600f8700d37fc637e223ced3aa8324f3650bf52242";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.2.0.tar.gz";
      hash = "sha256-dvit+yvc0MnipqWjxJdfIsA6fJaJZOaIpx4w4woCxbE=";
    };
  }
  {
    name = "12209db20ce873af176138b76632931def33a10539387cba745db72933c43d274d56";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.2.0.tar.gz";
      hash = "sha256-zcfZEMnipWDPuptl9UN0PoaJDjy2EHc7Wwi4GQq3hkY=";
    };
  }
  {
    name = "1220c90b2228d65fd8427a837d31b0add83e9fade1dcfa539bb56fd06f1f8461605f";
    path = fetchzip {
      url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.2.0.tar.gz";
      hash = "sha256-T+EZiStBfmxFUjaX05WhYkFJ8tRok/UQtpc9QY9NxZk=";
    };
  }
]
