name: genesis_shell
description: "Next-gen mobile & desktop compositor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 86e7e0be63f142fdb8d349bb05e34558b2b58646
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 86e7e0be63f142fdb8d349bb05e34558b2b58646
      path: packages/libtokyo_flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  bitsdojo_window: ^0.1.6
  intl: ^0.19.0
  backdrop: ^0.9.1
  upower: ^0.7.0
  args: ^2.5.0
  provider: ^6.1.2
  dbus: ^0.7.10
  flutter_svg: ^2.0.10+1
  path: ^1.9.0
  nm: ^0.5.0

dependency_overrides:
  meta: ^1.14.0
  intl: ^0.19.0
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: 86e7e0be63f142fdb8d349bb05e34558b2b58646
      path: packages/libtokyo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/wallpaper/desktop/
    - assets/wallpaper/mobile/
