name: genesis_shell
description: "Next-gen mobile & desktop compositor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  system_theme: ^2.3.1
  flutter_adaptive_scaffold: ^0.1.10+1
  bitsdojo_window: ^0.1.6
  intl: ^0.19.0
  backdrop: ^0.9.1
  upower: ^0.7.0
  args: ^2.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper/desktop/
    - assets/wallpaper/mobile/
